### ISSUE TITLE
Issues when Installing curvyRoute 

### ISSUE THREAD

**Issue by Brandon1419** [metrolab/curvyRoute#3]
Where exactly do I do this? "Add curvyRoute as dependency in the podspec of the module that contains the strings files:"

**Comment by zigzagg16** [comment]
Hey @Brandon1419 , sorry, it looks like it was a copy/paste from another project 🤦🏼‍♂️
You just have need to add curvyRoute specs to your Podfile:

`pod 'curvyRoute'`

then, run: `pod install`
